### PR TITLE
Add team photos with scrollbar to footer

### PR DESCRIPTION
**Pull request by rmehri01**
## :construction_worker: Changes

- Added team member information and photos to a scroll section in the footer

## :flashlight: Testing Instructions

- Amplify!

### CODE REVIEW

**Comment by kozr** [comment]
Wow this is a lot of work. Thanks! Could you make the component lazy? https://nuxtjs.org/docs/2.x/directory-structure/components
image

**Comment by rmehri01** [comment]
@kozr Wait so the only thing you have to do is prefix it with lazy? I can't really tell the difference but maybe that's because they're static.

**Comment by kozr** [comment]
image
also looks like you're missing a key

**Comment by kozr** [comment]
I also think the designs intended it to have animation. You can refer to the faq PR for some references.

**Comment by rmehri01** [comment]
@kozr It says this on the figma though:
image
Also styling scrollbars doesn't work on all browsers but should I do it anyways?

**Comment by kozr** [comment]
I'm also looking into the docs. It's kind of confusing and they don't go into details. I never realized design said no carousel oops. I think you should do it anyways so we don't have to come back later if design points it out.

**Comment by rmehri01** [comment]
> I'm also looking into the docs. It's kind of confusing and they don't go into details. I never realized design said no carousel oops. I think you should do it anyways so we don't have to come back later if design points it out. 

Alright sounds good!

**Comment by kozr** [comment]
Hope you don't mind, I pushed a commit to resize the images to 200px max.

**Comment by rmehri01** [comment]
> Hope you don't mind, I pushed a commit to resize the images to 200px max.

Oh okay, thank you!

**Review by kozr — APPROVED** [review]

**Comment by kozr** [comment]
I might add some algorithm to randomize the list.

**Comment by rmehri01** [comment]
> I might add some algorithm to randomize the list.

I can do that if you want, up to you!

**Comment by kozr** [comment]
@rmehri01 I can do it, try out some of the issues in https://github.com/nwplus/monorepo. If you want to pick one up, let's hop onto a call for a few minutes so I can explain what's going on and how it's going to work.

**Comment by kozr** [comment]
@rmehri01 I'm good with the changes. You can merge it when you feel it's good as well.

**Comment by rmehri01** [comment]
> @rmehri01 I'm good with the changes. You can merge it when you feel it's good as well.

Alright sounds good!

**Pull request merged**
