### PR TITLE
fix footer

### PR DESCRIPTION
**Pull request by kozr**
## :construction_worker: Changes

A brief summary of what changes were introduced.
Fix footer margins for mobile and desktop

## :thought_balloon: Notes

Any additional things to take into consideration.

## :flashlight: Testing Instructions

Explain how to test your changes, if applicable.

### CODE REVIEW

**Review by ItsAdel — CHANGES_REQUESTED** [review]
The changes look and work really well. Could you just update the desktop footer background image to match the new footer mobile background?

**Comment by kozr** [comment]
Wdym, it's identical to figma rn for desktop

**Comment by ItsAdel** [comment]
> Wdym, it's identical to figma rn for desktop

There's a few more people that added to the desktop footer section. Double check you are on the final version of the figma design. If you swtich between mobile and desktop, you'll notice missing people

**Comment by kozr** [comment]
Ah I see, good catch!!

**Review by ItsAdel — APPROVED** [review]

**Pull request merged**
