### PR TITLE
Bug patches

### PR DESCRIPTION
**Pull request by kozr**
## :construction_worker: Changes

A brief summary of what changes were introduced.
Fixed image sizing on desktop, stitching FAQ and sponsor, add mobile background, fixed transition between hero and about, fix transition between faq and footer.

## :thought_balloon: Notes

Any additional things to take into consideration.

## :flashlight: Testing Instructions

Explain how to test your changes, if applicable.

### CODE REVIEW

**Review by ItsAdel — APPROVED** [review]
In mobile view, there is a big brownish-grey section underneath the sponsor section. Other than that, everything looks good to me.

I tried getting rid of it on Monday but couldn't figure it out

**Comment by kozr** [comment]
I think it's from footer section, but I'll make a change in this sponsor pr anyways.

**Review by ItsAdel — CHANGES_REQUESTED** [review]
It looks great for desktop! Could you do something similar for mobile?

**Review by ItsAdel — APPROVED** [review]
It looks really good. Thanks for doing all this!

**Pull request merged**
