### PR TITLE
Implement FAQ animation

### PR DESCRIPTION
**Pull request by yehee**
:tickets: **Ticket(s)**: Closes #

---

## :construction_worker: Changes

A brief summary of what changes were introduced.

## :thought_balloon: Notes

- Includes `faq-hi-fi` and `hero` branch -- to be merged after #8 and #9 

## :flashlight: Testing Instructions

Explain how to test your changes, if applicable.

### CODE REVIEW

**Comment by kozr** [comment]
How many stats are we putting? @ItsAdel

**Comment by ItsAdel** [comment]
Still waiting for logs to get back to me with details about what stats to put on

**Comment by kozr** [comment]
I think we may be able to use 
image this field.

**Comment by ItsAdel** [comment]
Heard back from logs:

Temporary stats would be last year stats
Live stats would be number of applications, number of first time applicants, female applicants, etc
Last years stats is
https://www.notion.so/nwplus/Stats-a4da8172d699441fb5d870376b57876e
We don't have to be too specific like some descriptions in the notion doc

**Comment by kozr** [comment]
I'm taking over.

**Comment by kozr** [comment]
It's good to go from the serverless function side.

**Comment by kozr** [comment]
image
https://github.com/nwplus/Functions-new/pull/8 For reference

**Review by ItsAdel — APPROVED** [review]
Looked over all the changes and the new setup and its EPIC! Great work !!

**Review by ItsAdel — CHANGES_REQUESTED** [review]
Actually just noticed something really small. The text should not show up on the light purple inside border
image

**Pull request merged**
