### PR TITLE
Hi-Fi FAQ

### PR DESCRIPTION
**Pull request by kozr**
## :construction_worker: Changes

A brief summary of what changes were introduced.

- [x] Desktop popup style questions
- [x] Neon styling
- [x] Mobile responsiveness
- [x] Add other background images
- [x] Refactoring

## :thought_balloon: Notes

Any additional things to take into consideration.

## :flashlight: Testing Instructions

Explain how to test your changes, if applicable.
Play around with responsiveness and let me know what looks off!

### CODE REVIEW

**Comment by kozr** [comment]
#9

**Comment by kozr** [comment]
Waiting for design to get back to me on possibly extending the mobile version of FAQ so I could fit more in.

**Review by ItsAdel — CHANGES_REQUESTED** [review]
This looks amazing! Great work. I think it's just missing the animation where the down-pointing arrow turns into an upward-pointing arrow when you expand a faq item. We have something similar in https://2019.nwhacks.io/ and it would be cool if we did as well. The animation is a nice to have but the expanded faq section should have the arrow point up.

**Comment by kozr** [comment]
Got it, will work on it soon!

**Comment by kozr** [comment]
@yehee helped me implement it! What a pleasant surprise :)))

Edit: oops I was confused. I will get this animation in today.

**Comment by kozr** [comment]
Ready for review

**Review by rmehri01 — APPROVED** [review]
Looks really good! I don't know if this is just me but the font looks different than what I see on figma. They both say HK Grotesk so I'm not sure.

Mine: 
image

Figma:
image

**Comment by kozr** [comment]
image
Looks fine on Amplify @rmehri01  hmm.

**Comment by rmehri01** [comment]
Hmm weird, might just be me.

**Pull request merged**
